# -*- coding: utf-8 -*-
"""Question 2: Sentiment Analysis [25 marks].ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NnXhxMtvg98EVSYOnBU_v9EDtwIavn8P

Part 1: Data Loading [2 points]

1.Load the dataset Corona_NLP.csv [1]
"""

from google.colab import files
uploaded = files.upload()

"""2. Show the last 10 rows of the dataframe [1]"""

import pandas as pd
df2 = pd.read_csv('Corona_NLP.csv')
df2.tail(10)

df2.shape

"""Part 2: Manipulation and Visualisations [8 points]

1.Check if there are any duplicate rows. If there are any, remove the duplicates. [1]
"""

import pandas as pd

duplicate_rows = df2[df2.duplicated()]
df2 = df2.drop_duplicates()

df2.shape

"""2.(a) In the Location column, find unique values and their corresponding frequencies (number of times they appear) [1]"""

location_counts = df2['Location'].value_counts()
print(location_counts)

"""2.(b) Sort the values in descending order. [1]"""

location_counts = location_counts.sort_values(ascending=False)
print(location_counts)

"""2.(c) Using a bar chart, visualise your results for the top 20 locations. [1]"""

import matplotlib.pyplot as plt

location_counts = df2['Location'].value_counts()
top_20 = location_counts.head(20)

plt.figure(figsize=(12,6))
top_20.plot(kind='bar',color='#0174c3')
plt.title('Top 20 Locations by Frequency')
plt.xlabel('Location')
plt.ylabel('Frequency')

plt.show()

"""3.You will see that Sentiment can take 5 values: "Extremely Negative", "Negative", "Neutral", "Positive", "Extremely Positive". Using an appropriate color palette and an appropriate type of graph, visualise how Sentiment is distributed. [2]"""

sentiment_counts = df2['Sentiment'].value_counts()

sizes = sentiment_counts.values
labels = sentiment_counts.index
colors = ['#a8c686','#b07171','#0070ff','#00cc99','#b34b3e']

plt.figure(figsize=(8,8))
plt.pie(sizes,labels=labels,colors=colors,autopct='%1.1f%%')
plt.title('Sentiment Distribution')

plt.show()

"""4.Change the labels of part of the data, combining "Extremely Negative" and "Negative" into “Negative” and "Positive" and "Extremely Positive" into positive. [2]"""

df2['Sentiment'] = df2['Sentiment'].replace({"Extremely Negative":"Negative","Extremely Positive":"Positive"})

sentiment_counts = df2['Sentiment'].value_counts()

sizes = sentiment_counts.values
labels = sentiment_counts.index
colors = ['#a8c686','#b07171','#0070ff']

plt.figure(figsize=(8,8))
plt.pie(sizes,labels=labels,colors=colors,autopct='%1.1f%%')
plt.title('Sentiment Distribution(Combined)')

plt.show()

"""Part 3 - Cleaning [8 points]

1.Remove hyperlinks [1]
"""

import re

def remove_hyperlinks(text):
  text = text.lower()
  return text
  return re.sub("http?:\/\/[a-z0-9]+(?:\.[a-z0-9-]+)+[/?#]\s*","", str(text))

  df2['OriginalTweet'] = df2['OriginalTweet'].apply(remove_hyperlinks)
  df2

"""2.Remove hashtags [1]"""

def remove_hashtags(text):
  text = str(text) # 最早写的代码没有这一行，会报错，因为text里有浮点数，不能被re.sub()处理。在这里假设这句将text里非字符串的内容转换为字符串
  return re.sub(r'#\w+', '', text)

df2['OriginalTweet'] = df2['OriginalTweet'].apply(remove_hashtags)
df2

"""3.Replace \n and \r with an empty space [2]"""

df2['OriginalTweet'] = df2['OriginalTweet'].str.replace(r'[\n\r]+','',regex=True)
df2

"""4.Using TweetTokenizer in nltk.tokenize, perform tokenization. Sample code is provided. You can use another function if you wish. [1]"""

import nltk
from nltk.tokenize import TweetTokenizer

tokenizer = TweetTokenizer()

df2['TokenizedTweet'] = df2['OriginalTweet'].apply(lambda x: tokenizer.tokenize(x))
df2

"""5.In the same function, remove stopwords and punctuation signs. [1]"""

from nltk.corpus import stopwords
import string

tokenizer = TweetTokenizer()

nltk.download('stopwords')
stop_words = set(stopwords.words('english'))
punctuation = set(string.punctuation)

def process_tweet(tweet):
  new_tweet = tokenizer.tokenize(tweet)
  clean_tweet = [element for element in new_tweet
                 if element.lower() not in stop_words and element not in punctuation]
  return clean_tweet

df2['ProcessedTweet'] = df2['OriginalTweet'].apply(process_tweet)
df2

"""6.Perform stemming using PorterStemmer in nltk.stem [1]"""

from nltk.stem import PorterStemmer
import string

tokenizer = TweetTokenizer()
stemmer = PorterStemmer()

nltk.download('stopwords')
stop_words = set(stopwords.words('english'))
punctuation = set(string.punctuation)

def process_tweet(tweet):
  tokens = tokenizer.tokenize(tweet)
  filtered_tokens = [token for token in tokens if token.lower() not in stop_words and token not in punctuation]
  stemmed_tokens = [stemmer.stem(token) for token in filtered_tokens]
  return stemmed_tokens

df2['StemmedTweet'] = df2['OriginalTweet'].apply(process_tweet)
df2

"""7.Apply these functions to the dataset and visualise the first and last 5 rows. [1]"""

tokenizer = TweetTokenizer()
stemmer = PorterStemmer()

nltk.download('stopwords')
stop_words = set(stopwords.words('english'))
punctuation = set(string.punctuation)

def process_tweet(tweet):
  tokens = tokenizer.tokenize(tweet)
  filtered_tokens = [token for token in tokens if token.lower() not in stop_words and token not in punctuation]
  stemmed_tokens = [stemmer.stem(token) for token in filtered_tokens]

  return stemmed_tokens

df2['FinalTweet'] = df2['OriginalTweet'].apply(process_tweet)
df2

"""Part 4 - Model development [7]

1.Create a tf-idf vectorizer and fit the function. [1]
"""

import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
import nltk
from nltk.tokenize import TweetTokenizer
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer
import string

tokenizer = TweetTokenizer()
stemmer = PorterStemmer()

nltk.download('stopwords')
stop_words = set(stopwords.words('english'))
punctuation = set(string.punctuation)

def process_tweet(tweet):
  tokens = tokenizer.tokenize(tweet)
  filtered_tokens = [token for token in tokens if token.lower() not in stop_words and token not in punctuation]
  stemmed_tokens = [stemmer.stem(token) for token in filtered_tokens]

  return " ".join(stemmed_tokens)

df2['StemmedTweet'] = df2['OriginalTweet'].apply(process_tweet)

tfidf_vectorizer = TfidfVectorizer()

tfidf_matrix = tfidf_vectorizer.fit_transform(df2['StemmedTweet'])
tfidf_df = pd.DataFrame(tfidf_matrix.toarray(), columns = tfidf_vectorizer.get_feature_names_out())

"""2.Keeping only the columns Tweet and Sentiment, split your dataset into training (80%) and test (20%) sets. [1]"""

from sklearn.model_selection import train_test_split

df2_selected = df2[['StemmedTweet','Sentiment']]

train_df, test_df = train_test_split(df2_selected, test_size=0.2, random_state=42)

"""3.Build a logistic regression model and fit the data. [3]"""

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

train_df.dropna(inplace=True)
test_df.dropna(inplace=True)

x_train = train_df['StemmedTweet']
y_train = train_df['Sentiment']
x_test = test_df['StemmedTweet']
y_test = test_df['Sentiment']

tfidf_vectorizer = TfidfVectorizer()
x_train_tfidf = tfidf_vectorizer.fit_transform(x_train)
x_test_tfidf = tfidf_vectorizer.transform(x_test)

logistic_regression_model = LogisticRegression(random_state=42)
logistic_regression_model.fit(x_train_tfidf,y_train)

"""4.What is the accuracy of the model? [1]"""

y_pred = logistic_regression_model.predict(x_test_tfidf)
accuracy = accuracy_score(y_test,y_pred)

print("Accuracy of the logistic model:{:.2f}%".format(accuracy*100))

"""5.Generate a classification report. [1]"""

from sklearn.metrics import classification_report

classification_report = classification_report(y_test,y_pred, target_names=train_df['Sentiment'].unique())

print("Classification Report:\n",classification_report)